### PR TITLE
Fix for ActiveSupport 5.2

### PR DESCRIPTION
**Pull request by akappen**
- Backwards compatible with ActiveSupport 5.0
- ActiveSupport 5.0 no longer gets security fixes

ActiveSupport 5.2 callbacks no longer support evaluated strings in `:if` and `:unless` conditionals. The critic `callbacks.rb` `_normalize_callback_option` method sets an `:if` or `:unless` option string and violates this requirement.

In ActiveSupport 5.2 this error is raised:
```
Passing string to be evaluated in :if and :unless conditional options is not supported.
```

This patch fixes `_normalize_callback_option` to return a lambda that executes the same logic as the original evaluated string. The test suite passes fo ActiveSupport 3, 4, 5.0, and 5.2.

### CODE REVIEW

**Comment by akappen** [comment]
Since ActiveSupport 5.0 is no longer getting security patches it may make sense to bump the `Gemfile` to use `gem 'activesupport', '~> 5.2', require: false` and `critic.gemspec` to use `spec.add_dependency 'activesupport', '> 5.0', '< 6.0'`.

**Comment by akappen** [comment]
I didn't bump the gem `version.rb` file, not sure if that should be in this PR or if you'd like to bump it in a separate commit.

**Comment by thommahoney** [comment]
@lanej Would you be able to review & release this sometime this week? Alternatively, transferring ownership of this repo to `fastly` is an option. Whatever suits you.

**Comment by lanej** [comment]
@akappen ill release out of master.  thanks for calling that out.

**Comment by lanej** [comment]
Happy be done with the `eval` strings.

**Comment by lanej** [comment]
https://rubygems.org/gems/critic/versions/0.2.3

**Pull request merged**
